name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          use-mamba: true
          auto-activate-base: false
          activate-environment: "PoseBench-Documentation"
          environment-file: docs/.docs.environment.yaml
      - name: Install dependencies
        run: |
          $CONDA/envs/PoseBench-Documentation/bin/pip install -e .
      - name: Sphinx build
        run: |
          rm -rf docs/build/ && $CONDA/envs/PoseBench-Documentation/bin/sphinx-build docs/source/ docs/build/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true
